/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bdaea00d258d60976ebde118c189f8c8)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
