/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ef4394146b03074a236682afd17b0b45)
interface __BaseEnv_Env {
	VITE_SANITY_PROJECT_ID: "pqdr91mr";
	VITE_SANITY_DATASET: "production";
	VITE_SANITY_API_VERSION: "2024-02-13";
	VITE_SANITY_STUDIO_URL: "https://chrcit.com/studio";
	VITE_SANITY_STUDIO_PREVIEW_ORIGIN: "https://chrcit.com";
	SITE_URL: "https://chrcit.com";
	PRODUCTION_URL: "https://chrcit.com";
	SANITY_SESSION_SECRET: string;
	MAILERLITE_API_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_SANITY_PROJECT_ID" | "VITE_SANITY_DATASET" | "VITE_SANITY_API_VERSION" | "VITE_SANITY_STUDIO_URL" | "VITE_SANITY_STUDIO_PREVIEW_ORIGIN" | "SITE_URL" | "PRODUCTION_URL" | "SANITY_SESSION_SECRET" | "MAILERLITE_API_TOKEN">> {}
}
