import { defineField, defineType } from 'sanity';

export const thing = defineType({
  name: 'thing',
  title: 'Thing',
  type: 'document',
  groups: [
    { name: 'content', title: 'Content', default: true },
    { name: 'details', title: 'Details' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'kind',
      title: 'Kind',
      type: 'string',
      group: 'content',
      initialValue: 'book',
      options: {
        list: [
          { title: 'Book', value: 'book' },
          { title: 'Article', value: 'article' },
          { title: 'Film', value: 'film' },
          { title: 'Music', value: 'music' },
          { title: 'Album', value: 'album' },
          { title: 'Tool', value: 'tool' },
          { title: 'Game', value: 'game' },
          { title: 'Website', value: 'website' },
          { title: 'Other', value: 'other' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'creator',
      title: 'Author, artist, or maker',
      type: 'string',
      group: 'content',
    }),
    defineField({
      name: 'url',
      title: 'External URL',
      type: 'url',
      group: 'content',
      validation: (Rule) => Rule.uri({ scheme: ['http', 'https'] }),
    }),
    defineField({
      name: 'image',
      title: 'Cover or image',
      type: 'complexImage',
      group: 'content',
    }),
    defineField({
      name: 'summary',
      title: 'Short summary',
      type: 'text',
      rows: 3,
      group: 'content',
    }),
    defineField({
      name: 'notes',
      title: 'My notes',
      type: 'richText',
      group: 'content',
    }),
    defineField({
      name: 'topics',
      title: 'Topics',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'topic' }] }],
      group: 'details',
    }),
    defineField({
      name: 'year',
      title: 'Year',
      type: 'number',
      group: 'details',
    }),
    defineField({
      name: 'rating',
      title: 'Legacy rating',
      type: 'number',
      description: 'Imported historic rating. Optional for new entries.',
      group: 'details',
    }),
    defineField({
      name: 'category',
      title: 'Legacy category',
      type: 'string',
      group: 'details',
    }),
    defineField({
      name: 'tags',
      title: 'Freeform tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      group: 'details',
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      initialValue: false,
      group: 'details',
    }),
    defineField({
      name: 'sortOrder',
      title: 'Curated order',
      type: 'number',
      group: 'details',
    }),
    defineField({ name: 'meta', title: 'SEO', type: 'meta', group: 'seo' }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'creator', media: 'image.asset' },
  },
});
